### ISSUE TITLE
generated sql contains "double-quotes" around everything for Oracle DB?

### ISSUE THREAD

**Issue by sbitteker** [korma/Korma#285] opened 2015-03-10 15:49 UTC
Just trying out Korma for the first time. I had a BoneCP pool that I'm using, if it makes any difference.
The query generated is correct for Oracle 11g, if I paste it into a query tool and remove all the double-quotes. When running in the REPL I get a  ```Message: ORA-00904: "TEAM_NOTES"."note_type_id": invalid identifier.``` If it generated without the quotes it would work. i.e.```TEAM_NOTES.note_type_id```
But every table and column name has double quotes around them,

Since I'm not using the included C3PO, is there a (Oracle) dialect or something else I need to set to prevent the double quotes form being generated?

Thanks,
Steve

**Comment by ls4f** [comment] 2015-03-10 15:51
Sounds to me like your casing is incorrect and you simply 'drop' the case sensitivity without the quotes.

**Comment by sbitteker** [comment] 2015-03-10 16:37
I'm not sure what you mean. I don't have any "quoted strings" at all.

(defentity ntype
  (pk :TYPE_ID)
  (belongs-to pnotes {:fk :TYPE_ID})
  (many-to-many ntype :NOTE_TYPE { :rfk :TYPE_ID})
  (table :NOTE_TYPE))
  
(defentity ngroup
  (pk :GROUP_ID)
  (belongs-to pnotes {:fk :GROUP_ID})
  (many-to-many ngroup :NOTE_GROUP { :rfk :GROUP_ID})
  (table :NOTE_GROUP))

(defentity pnotes
  (pk :NOTE_ID)
  (table :NOTES)
  (belongs-to ntype {:fk :TYPE_ID})
  (belongs-to ngroup {:fk :GROUP_ID}))
  
  

(select pnotes)  --korma retuns ()   -- from a query tool. select * from notes  => returns 5 rows
(select pnotes (with ntype) (with ngroup))  =>  ORA-00904: "NOTES"."TYPE_ID": invalid identifier

The query korma generates is..
SELECT "NOTES".*, "NOTE_TYPE".*, "NOTE_GROUP".* 
FROM ("NOTES" LEFT JOIN "NOTE_TYPE" ON "NOTE_TYPE"."TYPE_ID" = "NOTES"."TYPE_ID") 
LEFT JOIN "NOTE_GROUP" ON "NOTE_GROUP"."GROUP_ID" = "NOTES"."GROUP_ID"

If I change all defentity's to lower case (i.e. table name and column keywords, etc.) it still generates the same query as above only all is lowercase with the same double-quotes.

Oracle doesn't like the Quotes around column and table names. Korma shouldn't create the query with double quotes around everything. How to configure Korma to remove them?

**Comment by ls4f** [comment] 2015-03-10 16:53
I assume the case sensitivity in Korma is by design. Haven't used Oracle myself but a quick search spits out things lilke http://stackoverflow.com/questions/1162381/how-do-i-escape-a-reserved-word-in-oracle , which say using double quotes does exactly what I expect it to do - make the engine treat names as case sensitive.
Are you absolutely sure the table name is `NOTE_TYPE` and not `note_type`? You could simply specify a suitable naming strategy.

**Comment by sbitteker** [comment] 2015-03-10 17:21
Yikes, the sql exception was due to a typo. Now not getting any data back with a simple (select pnotes) and all other queries with ```(with ngroup)```

**Comment by ls4f** [comment] 2015-03-10 17:28
Might have some error in the relations ... don't use them too much and can't help there.
Definitely think it's a bad idea, but if you want to remove the double quotes any way, you could try specifying `:delimiters ["" ""]` in the options.

**Comment by sbitteker** [comment] 2015-03-10 17:35
Running with as-sql and pasting into the sql tool returns rows. The REPL returns ().

SELECT "NOTES".* FROM "NOTES"   is what (as-sql) returns, so I don't think it's a relationship issue unless korma is doing something other that what is shown in the returned sql. Probably not likely.  This is the only db with these new tables and connectivity is there as well due to the oracle exception earlier. hmm?

**Comment by immoh** [comment] 2015-03-11 07:43
I don't see anything wrong with your code right away. If you're not getting an exception, it means your query is properly executed. Are you sure the data is committed and the user you're connecting with is authorized to see it?

You could:
* Try selecting count from the table using exec-raw: `(exec-raw "SELECT COUNT(1) FROM \"NOTES\"")`
* Try inserting a row to the table using Korma and see if you get it back using select

**Closed** 2015-04-30 09:29 UTC
